baseURL = 'https://example.org/'
defaultContentLanguage = 'zh-hant'
defaultContentLanguageInSubdir = true
theme = 'event'

[languages]
	[languages.zh-hant]
		languageName = 'ç¹é«”ä¸­æ–‡'
		weight = 1
		contentDir = 'content'
	    title = 'OpenTechConf'
		languageCode = 'zh-hant'
		params.locale = 'zh-Hant'
		[languages.zh-hant.params.themes.event]
			location = 'AWS é¦™æ¸¯è¾¦å…¬å®¤'
			slogan = 'OpenTechConf æœƒè­°'
			description = '''
OpenTechConf æ˜¯ä¸€å€‹å°ˆæ³¨æ–¼é–‹æ”¾æŠ€è¡“çš„æœƒè­°ã€‚
æˆ‘å€‘å¸Œæœ›æ‚¨äº«å—ä½¿ç”¨é€™å€‹ä¸»é¡Œï¼ğŸ‰
'''
			directions = '''
ä½¿ç”¨å…¬å…±äº¤é€šåˆ°é”æœƒå ´çš„è·¯ç·šæŒ‡å—ã€‚
æ‚¨å¯ä»¥åœ¨ Hugo é…ç½®æ–‡ä»¶ä¸­è‡ªè¨‚æ­¤ä½”ä½æ–‡å­—ï¼Œæˆ–å¦‚æœä¸éœ€è¦å‰‡ç§»é™¤å®ƒã€‚
'''
			aboutUs = '''
æ›´å¤šé—œæ–¼æ´»å‹•çš„è³‡è¨Šå°‡å¾ˆå¿«æ·»åŠ ã€‚æ•¬è«‹æœŸå¾…ï¼ğŸ‰
'''
	[languages.en]
		languageName = 'English'
		weight = 2
		contentDir = 'content'
	    title = 'OpenTechConf'
		languageCode = 'en'
		params.locale = 'en'
		[languages.en.params.themes.event]
			location = 'AWS Office, Hong Kong'
			slogan = 'A Conference for Open Technology'
			description = '''
OpenTechConf is a conference focused on open technology.
We hope you enjoy using this theme! ğŸ‰
'''
			directions = '''
Directions for getting to the location using public transportation.
Customize this placeholder text in your Hugo configuration file or remove it if not needed.
'''
			aboutUs = '''
More information about the event will be added soon. Stay tuned! ğŸ‰
'''

[params.themes.event]
    startDate = '2025-09-13T10:00:00+08:00'
    endDate = '2025-09-13T18:00:00+08:00'